name: 10b - entornos ramas protegidas
on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:
jobs:
  entornos:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Verificar variable
        run: echo "${{vars.UNA_VARIABLE}}"
      - name: Verificar secreto
        run: echo "${{secrets.UN_SECRETO}}"
