name: 11b[llamante] - Ejercicio de workflow reutilizable
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/11b-npm-build-llamado.yml # uses: owner/repo@version
    with:
      versiones-node: "['16','18','20']"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: despliegue
        run: echo "Desplegando en AWS..." 
