name: 14b - Ejercicio docker dados
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  uso-compuesto:
    runs-on: ubuntu-latest
    name: Uso acci√≥n docker python
    steps:
      - id: docker
        uses: brainsdevops/gha-dockerpy-dice@v1
        with:
          numero-dados: 'dos'
      - name: Dado 1
        run: |
          echo "Resultado dado 1 es:  ${{steps.docker.outputs.dado1}}"
      - name: Dado 2
        run: |
          echo "Resultado dado 2 es:  ${{steps.docker.outputs.dado2}}"