name: 15a - Inyección de código
on:
  issues: 
    types:
      - opened
jobs:
  inyeccion:
    runs-on: ubuntu-latest
    steps:
      - run: |
          title="${{ github.event.issue.title }}"
          echo ${title}

