name: 15a - Inyección de código
on:
  issues: 
    types:
      - opened
jobs:
  inyeccion:
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }} #
    steps:
      # - run: |
      #     title="${{ github.event.issue.title }}"
      #     echo ${title}
      - run: |
          echo "${ISSUE_TITLE}"

