name: 15c - Otros repositorios
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  listar-repos:
    name: Listar repos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
    - name: List repos
      env:
        GH_TOKEN: ${{ github.token }}
        #GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: gh repo list ${{ github.repository_owner }} --visibility private
    - name: View repos
      env:
        # GH_TOKEN: ${{ github.token }}
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: gh repo view ${{ github.repository_owner }}/gha-composite-action